import {
    Thermometer, Droplets, Activity, ShieldBan, MapPin, Bell, FileText,
    Truck, Cpu, Eye, Globe, Zap, Shield, ShieldCheck, ShieldAlert,
    ClipboardCheck, Box, Warehouse, Sprout, Waves, Beef, Stethoscope,
    Ship, Anchor, Sun, TrendingUp, ChartLine, CircleCheckBig,
    DatabaseZap, AlertTriangle, Clock, Search, TrendingDown, UserCheck,
    Building2, HardHat, Factory, Lightbulb, Smartphone, Cloud,
    HeartPulse, Navigation, Users, Bird, Dog, Map, Scale,
    Microscope, Battery, CloudLightning, HardDrive, Package,
    Settings2, BarChart, Expand, type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
    thermometer: Thermometer,
    droplets: Droplets,
    activity: Activity,
    'shield-ban': ShieldBan,
    'map-pin': MapPin,
    bell: Bell,
    'file-text': FileText,
    truck: Truck,
    cpu: Cpu,
    eye: Eye,
    globe: Globe,
    zap: Zap,
    shield: Shield,
    'shield-check': ShieldCheck,
    'shield-alert': ShieldAlert,
    'clipboard-check': ClipboardCheck,
    box: Box,
    warehouse: Warehouse,
    sprout: Sprout,
    waves: Waves,
    beef: Beef,
    stethoscope: Stethoscope,
    ship: Ship,
    anchor: Anchor,
    sun: Sun,
    'trending-up': TrendingUp,
    'chart-line': ChartLine,
    'circle-check-big': CircleCheckBig,
    'database-zap': DatabaseZap,
    'alert-triangle': AlertTriangle,
    clock: Clock,
    search: Search,
    'trending-down': TrendingDown,
    'user-check': UserCheck,
    'building-2': Building2,
    'hard-hat': HardHat,
    factory: Factory,
    lightbulb: Lightbulb,
    smartphone: Smartphone,
    cloud: Cloud,
    'heart-pulse': HeartPulse,
    navigation: Navigation,
    users: Users,
    bird: Bird,
    dog: Dog,
    map: Map,
    scale: Scale,
    microscope: Microscope,
    battery: Battery,
    'cloud-lightning': CloudLightning,
    'hard-drive': HardDrive,
    package: Package,
    'settings-2': Settings2,
    'bar-chart': BarChart,
    expand: Expand,
};

export function getIcon(name: string): LucideIcon {
    return iconMap[name] || Thermometer;
}

export const availableIcons = Object.keys(iconMap);
